sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t sterrell6/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sterrell6/docker-react npm run test




